jenkinsci/embeddable-build-status-plugin

src/main/java/org/jenkinsci/plugins/badge/StatusImage.java
According to RFC 7232, an ETag header must be a quoted string.
http://tools.ietf.org/html/rfc7232#section-2.3
Client libraries with strictly typed header handling (like Rust's [hyper](http://hyper.rs/hyper/hyper/header/struct.EntityTag.html)) will therefore consider an ETag without quotes invalid.
=> Fixed ETag header

src/main/java/org/jenkinsci/plugins/badge/ImageResolver.java, src/main/webapp/status/build-aborted-lightgrey-flat.svg, src/main/webapp/status/build-aborted-lightgrey.svg
suggested solution for: JENKINS-19319 Distinguish between Aborted and Failed in the status icon
https://issues.jenkins-ci.org/browse/JENKINS-19319
I added two new svg images to be able to distinguish between failed and aborted jobs.
The images are exact copies of the already existing unknown images, only changed the unknown text to aborted.
In the ImageResolver I added the two new filenames to the two existing styles.
I've added them in the second to last place because it seemed logical to me to have the image of the default case , which is "unknown", still at the last slot.
I did not touch are add any test for this change.
=> [JENKINS-19319] Distinguish between Aborted and Failed in the status icon

src/main/java/org/jenkinsci/plugins/badge/BadgeAction.java, src/main/java/org/jenkinsci/plugins/badge/PublicBadgeAction.java, src/main/java/org/jenkinsci/plugins/badge/RunBadgeAction.java, src/main/resources/org/jenkinsci/plugins/badge/BadgeAction/index.groovy, src/main/resources/org/jenkinsci/plugins/badge/BadgeAction/index.properties, src/main/resources/org/jenkinsci/plugins/badge/RunBadgeAction/index.groovy, src/main/resources/org/jenkinsci/plugins/badge/RunBadgeAction/index.properties, src/test/java/org/jenkinsci/plugins/badge/PublicBadgeActionTest.java
Instead of doing the image, nice to have it just return text.
Thus the icon's description was chosen.
=> New endpoint 'text' to return icon description

pom.xml
update the `<url>` field so that plugin docs points to GitHub
see https://jenkins.io/blog/2019/10/21/plugin-docs-on-github/#how-to-enable-github-documentation-for-your-plugin
=> move docs to GitHub

Jenkinsfile, pom.xml, src/main/java/org/jenkinsci/plugins/badge/extensions/SpecialValueParameterResolverExtension.java
Require Jenkins 2.332.4 or newer, since Jenkins 2.332.4 is the oldest LTS release with no open security advisory.
- Prepare to test with multiple Java versions
- Prevent NPE on null run description
- Require Jenkins 2.332.4 or newer
- Test Java 11 and Java 17 in CI
Also recommended by [developer documentation](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/#currently-recommended-versions).
=> Require Jenkins 2.332.4, build with Java 8, 11, or 17

pom.xml
Fix incorrect version number `${revision}231.v678984136a_0b_` generated by prior release.
See https://github.com/jenkins-infra/update-center2/pull/618 for the update center pull request to suspend distribution of the nonsense version number.
=> [JENKINS-69019] Use expected version number

src/main/java/org/jenkinsci/plugins/badge/StatusImage.java, src/main/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusAction.java
Replaces deprecated APIs:
- `Jenkins.getInstance()` --> `Jenkins.get()` (+ no `null`-check needed)
- `ACL.impersonate()` --> `ACL.as2`
There's an [_`extends Plugin`_](https://github.com/jenkinsci/embeddable-build-status-plugin/blob/master/src/main/java/org/jenkinsci/plugins/badge/PluginImpl.java) left, but I don't know how to replace this in a compatible manner. 
-----------------------------------
=> Replace deprecated APIs

src/main/java/org/jenkinsci/plugins/badge/StatusImage.java, src/test/java/org/jenkinsci/plugins/badge/StatusImageTest.java
- Add more StatusImage tests to assure compatibility
- Read default font only once for faster performance
Read default font only once for faster performance
JMeter test runs indicate that a single initialization of the default font reduces the HTTP response time by more than 50% and increases the throughout by more than 2x.
JMeter test runs were not exhaustive (30000 samples using a Linux controller running in a Docker container with the JMeter test from my Windows desktop), but they showed similar or better results on multiple runs.
Average response time before the change was 15ms. Average response time after the change ranged from 3-8 ms.
Median response time before the change was 10 ms. Median response time after the change was 2-3 ms with one 7ms outlier.
Throughput before the change …
=> Read default font only once

src/test/java/org/jenkinsci/plugins/badge/StatusImageTest.java
Windows computers in my CI cluster report slightly different values for text widths than the Windows computers on ci.jenkins.io.
Linux and other computers report same values.
Specific values are not as important as keeping the width value within a reasonable range.
- Allow range of width values in tests
Other changes included in the pull request include:
- Remove unused imports from test code
- Move PNG content type test code together
- Remove variable portion of image path from test
None of those other improvements are substantial enough to justify a separate pull request.
=> Allow range of width values in tests

pom.xml, src/main/java/org/jenkinsci/plugins/badge/actions/JobBadgeAction.java, src/main/java/org/jenkinsci/plugins/badge/actions/RunBadgeAction.java
The change proposed replaces the left-over tango icon reference with an ionicon one.
Before:
After:
=> Replace tango icons with ionicons

pom.xml, src/test/java/org/jenkinsci/plugins/badge/extensions/BuildIdRunSelectorExtensionTest.java
Adds 100% test coverage for one of the classes from the `extension` package.
Aims to address the [issue](https://github.com/jenkinsci/embeddable-build-status-plugin/issues/114) in smaller steps.
=> Improve automated test coverage #114 - Add test for BuildIdRunSelector extension

pom.xml
The mockito library is only used in tests so it should be scoped to tests.
Prevent unnecessary inclusion of mockito and its dependencies in the final hpi file.
=> Exclude mockito from packaging

src/test/java/org/jenkinsci/plugins/badge/JobBadgeActionFactoryTest.java, src/test/java/org/jenkinsci/plugins/badge/ParameterResolverTest.java, src/test/java/org/jenkinsci/plugins/badge/RunBadgeActionFactoryTest.java
Adds tests for the following classes in the default package.
* JobBadgeActionFactory
* RunBadgeActionFactory
* ParameterResolver - Added test for the example given in README. Would be great, if you can help add more use cases here.
Aims to address the https://github.com/jenkinsci/embeddable-build-status-plugin/issues/114 in smaller steps.
=> Improve automated test coverage #114 - Add test for classes in default package

src/main/java/org/jenkinsci/plugins/badge/extensions/BuildParameterRunSelectorExtension.java, src/test/java/org/jenkinsci/plugins/badge/extensions/BuildParameterRunSelectorExtensionTest.java, src/test/java/org/jenkinsci/plugins/badge/extensions/SpecialValueParameterResolverExtensionTest.java
Adds tests for the following classes in the extensions package.
* SpecialValueParameterResolverExtension
* BuildParameterRunSelectorExtension
Aims to address the https://github.com/jenkinsci/embeddable-build-status-plugin/issues/114 in smaller steps.
=> Improve automated test coverage #114 - Add test for classes in extensions package

src/main/java/org/jenkinsci/plugins/badge/extensions/SpecialValueParameterResolverExtension.java, src/test/java/org/jenkinsci/plugins/badge/extensions/SpecialValueParameterResolverExtensionTest.java
Test `shouldResolveDescription` in `SpecialValueParameterResolverExtensionTest.java` had an ignore stating "Runs into an infinite loop. Needs debugging.":
```java
@Ignore("Runs into an infinite loop. Needs debugging.")
void shouldResolveDescription() {
when(mockRun.getDescription()).thenReturn("run description");
String actualParameter = extension.resolve(mockRun, "description");
assertThat(actualParameter, is("run description"));
}
```
This is because the `resolve` method replaces "description" with "run description" and then checks if "run description" has the string "description" in it, and if so, replaces "description" with "run descriptions", and so on.
It turns out, a loop was not needed (and indeed, the regex that was used to control the loop).
Also, from a glance at the code and …
=> Prevent loop when parameter value contains parameter name

.vscode/settings.json, pom.xml, src/test/java/org/jenkinsci/plugins/badge/ImageResolverTest.java
This merge has 3 unit tests covering Ball Logic, First Test sees if the default 32x32 image logic is correct. The second is just a regular ball, and 3rd is an empty test case. I also Updated Mockito so it works with Final classes.  Still need to cover non-ball image requests but will handle that at a later time.  #114 
-  [x] Ensure that the pull request title represents the desired changelog entry
=> Add tests for ball logic in image resolver page 

src/main/resources/org/jenkinsci/plugins/badge/actions/JobBadgeAction/index.groovy, src/main/resources/org/jenkinsci/plugins/badge/actions/RunBadgeAction/index.groovy
This PR introduces the one-column layout we already use for various pages in core, which don't have a sidebar, yet take up the space of a sidebar:
Before:
After:
=> Use one-column layout

src/main/resources/org/jenkinsci/plugins/badge/actions/JobBadgeAction/ClickHandler.js, src/main/resources/org/jenkinsci/plugins/badge/actions/JobBadgeAction/index.groovy, src/main/resources/org/jenkinsci/plugins/badge/actions/RunBadgeAction/index.groovy, src/main/webapp/css/design.css
This PR picks up the last paragraph of #167 and removes inline page modification, but delivers the underlying change too.
JavaScript is now loaded via stapler adjuncts and page decoration has been moved to a dedicated CSS file loaded separately, as advised by our documentation.
=> [JENKINS-70602] Do not overwrite system font on examples page

.gitignore, CONTRIBUTING.md, src/test/java/org/jenkinsci/plugins/badge/EmbeddableBadgeConfigTest.java
added some simple tests for EmbeddableBadgeConfig. ref #114
=> Add EmbeddableBadgeConfig tests

pom.xml, src/main/java/org/jenkinsci/plugins/badge/EmbeddableBadgeConfig.java, src/main/java/org/jenkinsci/plugins/badge/IconRequestHandler.java, src/main/java/org/jenkinsci/plugins/badge/ImageResolver.java, src/main/java/org/jenkinsci/plugins/badge/ParameterResolver.java, src/main/java/org/jenkinsci/plugins/badge/StatusImage.java, src/main/java/org/jenkinsci/plugins/badge/actions/EmbeddableBadgeConfigsAction.java, src/main/java/org/jenkinsci/plugins/badge/actions/JobBadgeAction.java, src/main/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusAction.java, src/main/java/org/jenkinsci/plugins/badge/actions/RunBadgeAction.java, src/main/java/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStep.java, src/main/java/org/jenkinsci/plugins/badge/extensions/BuildIdRunSelectorExtension.java, src/main/java/org/jenkinsci/plugins/badge/extensions/BuildParameterResolverExtension.java, src/main/java/org/jenkinsci/plugins/badge/extensions/BuildParameterRunSelectorExtension.java, src/main/java/org/jenkinsci/plugins/badge/extensions/SpecialValueParameterResolverExtension.java, src/test/java/org/jenkinsci/plugins/badge/EmbeddableBadgeConfigTest.java, src/test/java/org/jenkinsci/plugins/badge/ImageResolverTest.java, src/test/java/org/jenkinsci/plugins/badge/ParameterResolverTest.java, src/test/java/org/jenkinsci/plugins/badge/StatusImageTest.java, src/test/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusActionTest.java, src/test/java/org/jenkinsci/plugins/badge/extensions/SpecialValueParameterResolverExtensionTest.java
Google Java Format is an excellent formatter for 2-space, 100 line codebases. Its [Rectangle Rule](https://github.com/google/google-java-format/wiki/The-Rectangle-Rule) has a high degree of conceptual purity, and this works well in the context of 2-space, 100 line codebases where it was designed. If starting from scratch, or if radical changes to existing code style were on the table, this would be my ideal formatter.
For existing 4-space, 120 line codebases where radical changes to existing code style are not on the table, Google Java Format has some critical flaws. Its 4-space "AOSP" mode does not work well at all, and it was not the primary use case. In practice the combination of 4-space mode and the rectangle rule results in unreadable code for lambdas. I have complained about this …
=> Format code with Palantir Java Format

.github/dependabot.yml, Jenkinsfile, pom.xml
- Test Jenkins 2.407 on ci.jenkins.io
- Require Jenkins 2.387.3 or newer
- Use plugin BOM 2133.v2e6c00fe4d61
Verified plugin tests run successfully on Linux Java 11 with Jenkins 2.387.3 as minimum Jenkins version.  Will rely on ci.jenkins.io to verify Windows with Java 17 and Jenkins 2.407.
=> Require Jenkins 2.387.3 or newer

src/main/resources/org/jenkinsci/plugins/badge/actions/JobBadgeAction/index.groovy, src/main/resources/org/jenkinsci/plugins/badge/actions/RunBadgeAction/index.groovy
In 2.401, we have removed `l:css` from core, when we dropped the dependency on `jenkins-js-modules`. Therefore, `l.css`, the groovy equivalent, is gone too, but it appears the two plugins using groovy views weren't updated.
Hence, I'm filing this PR retrospectively.
Without my change proposed, the embeddable build status page looks like:
as you can see it on ci.jenkins.io and 2.401.x
In groovy, `link` is equal to the HTML tag `<link>`, this PR makes use of, working independently of Jenkins versions.
=> Adapt 'l.css' removal in Jenkins 2.401 onwards

src/test/java/org/jenkinsci/plugins/badge/IconRequestHandlerTest.java
Added Test cases for one method. 
Jira issue - [JENKINS-70464](https://issues.jenkins.io/browse/JENKINS-70464)
=> [JENKINS-70464] Test the IconRequestHandler

src/main/java/org/jenkinsci/plugins/badge/EmbeddableBadgeConfig.java, src/main/java/org/jenkinsci/plugins/badge/ImageResolver.java, src/main/java/org/jenkinsci/plugins/badge/StatusImage.java, src/main/java/org/jenkinsci/plugins/badge/actions/EmbeddableBadgeConfigsAction.java, src/main/java/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStep.java, src/main/java/org/jenkinsci/plugins/badge/extensions/BuildIdRunSelectorExtension.java, src/main/java/org/jenkinsci/plugins/badge/extensions/BuildParameterRunSelectorExtension.java, src/test/java/org/jenkinsci/plugins/badge/JobBadgeActionFactoryTest.java, src/test/java/org/jenkinsci/plugins/badge/extensions/BuildParameterRunSelectorExtensionTest.java
Minor refactoring:
* use `switch` instead of if-else 
* use `StandardCharsets` instead of strings
* use diamond operator 
* and removed obsolete semicolons and imports
Ran all unit tests and played with it in a debug environment
```[tasklist]
```
=> Minor refactoring and character set cleanup

src/test/java/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStepTest.java
In response #114, 
- `AddEmbeddableBadgeConfigStepTest.java`
- currently, test coverage is as shown below
After changes, test coverage stands as shown below
```[tasklist]
```
=> [JENKINS-70464] Test `AddEmbeddableBadgeConfigStep`

src/test/java/org/jenkinsci/plugins/badge/actions/RunBadgeActionJenkinsRuleTest.java, src/test/java/org/jenkinsci/plugins/badge/actions/RunBadgeActionTest.java
Added Test cases
Jira issue - [JENKINS-70464](https://issues.jenkins.io/browse/JENKINS-70464)
=> Add a test for RunBadgeAction

src/test/java/org/jenkinsci/plugins/badge/actions/EmbeddableBadgeConfigsActionTest.java
In response to #114, 
- added `EmbeddableBadgeConfigsActionTest.java`
- Test coverage shown below
```[tasklist]
```
=> [JENKINS-70464] Test `EmbeddableBadgeConfigsAction`

src/main/java/org/jenkinsci/plugins/badge/extensions/BuildIdRunSelectorExtension.java, src/main/java/org/jenkinsci/plugins/badge/extensions/BuildParameterRunSelectorExtension.java
Instead of using `Bolean` and `Integer`, just use primitive types
Tested locally with `hpi:run` and ran Unit Tests
```[tasklist]
```
=> Use primitive types

src/test/java/org/jenkinsci/plugins/badge/EmbeddableBadgeConfigTest.java, src/test/java/org/jenkinsci/plugins/badge/ImageResolverTest.java, src/test/java/org/jenkinsci/plugins/badge/JobBadgeActionFactoryTest.java, src/test/java/org/jenkinsci/plugins/badge/StatusImageTest.java
The wildcard imoprt is more difficult to read.
Thanks to OpenRewrite for the steps that started this change.
https://docs.openrewrite.org/recipes/java/testing/junit5/usehamcrestassertthat
Confirmed tests pass with Java 21 on Linux.
=> Prefer non-wildcard imports, even for tests

README.md, src/main/resources/org/jenkinsci/plugins/badge/actions/JobBadgeAction/index.jelly, src/main/resources/org/jenkinsci/plugins/badge/actions/JobBadgeAction/index.properties, src/main/resources/org/jenkinsci/plugins/badge/actions/RunBadgeAction/index.jelly, src/main/resources/org/jenkinsci/plugins/badge/actions/RunBadgeAction/index.properties
- Minor grammar fix
- Replace <b> tags with <strong>, stop using color in text
Checked that rendering of the HTML pages looks as expected in both light and dark themes.
=> Replace <b> tags with <strong>, stop using color in text

README.md
Extension points are only interesting to plugin developers.  Place their documentation at the end of the documentation so that it does not disrupt reading by most users.
Confirmed page looks reasonable in web browser
=> Combine extension point documentation

README.md
Heading levels were inconsistent.  That makes reading more difficult for users.  Switch to consistent headings.
Confirmed that page rendering looks good on GitHub.
=> Use consistent documentation headings

src/main/resources/org/jenkinsci/plugins/badge/actions/JobBadgeAction/ClickHandler.js, src/main/webapp/css/design.css
`ClickHandler.js` is no longer used/nor loaded anywhere, nor are the related CSS selectors. Was previously used in https://github.com/jenkinsci/embeddable-build-status-plugin/pull/169 but the method of copying URLs was replaced in https://github.com/jenkinsci/embeddable-build-status-plugin/pull/222.
* Plugin works as before
```[tasklist]
```
=> Remove unused file and CSS selectors

pom.xml, src/spotbugs/excludesFilter.xml
Includes suppressions of the CT_CONSTRUCTOR_THROW warning because Jenkins plugins are not generally vulnerable to a Finalizer attack.
=> Use spotbugs plugin 4.8.2.0

src/main/resources/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStep/help-animatedOverlayColor.html, src/main/resources/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStep/help-color.html, src/main/resources/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStep/help-id.html, src/main/resources/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStep/help-link.html, src/main/resources/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStep/help-status.html, src/main/resources/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStep/help-subject.html, src/main/resources/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStep/help.html
Online help text is copied from the help page of the plugin.
Confirmed that the new online help text is visible in the Pipeline help page of the running Jenkins instance.
No automated tests created.  If additional time is available, it is more valuable to provide broader examples or more interesting samples.
```[tasklist]
```
=> Add online help for addEmbeddableBadgeConfig Pipeline step

src/test/java/org/jenkinsci/plugins/badge/extensions/BuildParameterResolverExtensionTest.java
In response to #114, 
- added `BuildParameterResolverExtensionTest.java`
- Test coverage shown below
```[tasklist]
```
=> [JENKINS-70464] Test `BuildParameterResolverExtensionTest` 

src/test/java/org/jenkinsci/plugins/badge/actions/EmbeddableBadgeConfigsActionTest.java
In response to #114, 
- Increased the test coverage of existing `EmbeddableBadgeConfigsActionTest.java`
- Improved test coverage shown below
```[tasklist]
```
=> [JENKINS-70464] Improve `EmbeddableBadgeConfigsActionTest` test coverage

src/test/java/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStepTest.java
In response to #114 
- Increased the test coverage of existing `AddEmbeddableBadgeConfigStepTest.java`
- Improved test coverage shown below
```[tasklist]
```
=> [JENKINS-70464] Improve `AddEmbeddableBadgeConfigStepTest` test coverage

src/main/java/org/jenkinsci/plugins/badge/actions/JobBadgeAction.java, src/main/java/org/jenkinsci/plugins/badge/actions/RunBadgeAction.java, src/test/java/org/jenkinsci/plugins/badge/actions/RunBadgeActionTest.java
Closes #278 
Replaced the `getReferer()` method with `getRequestURL()` (I am not sure if it is the optimal way to do it, but it fixes the issue without any flaws). Also modified the test cases to use getRequestURL() with and without `badge/` at the end of the URL.
Before:
Now:
https://github.com/jenkinsci/embeddable-build-status-plugin/assets/107404972/76d047cb-1779-44c1-980a-95980c1c8175
```[tasklist]
```
=> Resolve incorrect badge examples when opened directly from URL

pom.xml, src/test/java/org/jenkinsci/plugins/badge/extensions/SpecialValueParameterResolverExtensionTest.java
I have tried to increase the branch coverage in the Specialvalueparameterresolverextensiontest class form 33% to 50%
Automated tests pass
=> Add tests to SpecialValueParameterResolverExtensionTest

src/test/java/org/jenkinsci/plugins/badge/ParameterResolverTest.java
Added more automated tests and increased coverage for ParameterResolver class
=> Add ParameterResolver tests

pom.xml, src/main/java/org/jenkinsci/plugins/badge/EmbeddableBadgeConfig.java, src/main/java/org/jenkinsci/plugins/badge/StatusImage.java, src/main/java/org/jenkinsci/plugins/badge/actions/EmbeddableBadgeConfigsAction.java, src/main/java/org/jenkinsci/plugins/badge/actions/JobBadgeAction.java, src/main/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusAction.java, src/main/java/org/jenkinsci/plugins/badge/actions/RunBadgeAction.java, src/main/java/org/jenkinsci/plugins/badge/extensions/BuildParameterResolverExtension.java, src/main/java/org/jenkinsci/plugins/badge/extensions/SpecialValueParameterResolverExtension.java, src/test/java/org/jenkinsci/plugins/badge/actions/RunBadgeActionTest.java
Used OpenRewrite to convert to Java 17 syntax
ran `mvn clean verify`
Confirmed that [coverage badges extension plugin](https://github.com/jenkinsci/coverage-badges-extension-plugin) (the only plugin dependent on this plugin) passes its automated tests with the incremental build of this plugin
=> Require Jenkins 2.479.1 or newer

src/main/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusAction.java, src/test/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusActionTest.java
Increased test coverage for PublicBuildStatusActionTest class
=> Add test for PublicBuildStatusAction to increase coverage

src/main/java/org/jenkinsci/plugins/badge/StatusImage.java, src/test/java/org/jenkinsci/plugins/badge/StatusImageTest.java
Fixes a performance issue where font loading in StatusImage was blocking all threads during class initialization. 
Replaces the static initializer with thread-safe lazy loading and adds comprehensive test coverage.
* `mvn clean verify`
* `mvn hpi:run` for interactive testing
=> Improve font loading performance

pom.xml, src/test/java/org/jenkinsci/plugins/badge/extensions/BuildParameterRunSelectorExtensionTest.java
[JENKINS-70464](https://issues.jenkins.io/browse/JENKINS-70464?jql=labels%20%3D%20newbie-friendly%20and%20status%20in%20(Open%2C%20%22To%20Do%22%2C%20Reopened))
=> [JENKINS-70464] Improve embeddable build status plugin test coverage
