jenkinsci/embeddable-build-status-plugin

.gitignore
pom.xml
src/main/java/org/jenkinsci/plugins/badge/BadgeAction.java
src/main/java/org/jenkinsci/plugins/badge/BadgeActionFactory.java
src/main/java/org/jenkinsci/plugins/badge/PublicBadgeAction.java
src/main/java/org/jenkinsci/plugins/badge/RunBadgeAction.java
src/test/java/org/jenkinsci/plugins/badge/WorkflowBadgeActionTest.java

Manually tested as well
JIRA link: https://issues.jenkins-ci.org/browse/JENKINS-28642
@reviewbybees

[JENKINS-28642] Workflow compatibility for embeddable build status

---

src/main/java/org/jenkinsci/plugins/badge/PublicBuildStatusAction.java
src/main/resources/org/jenkinsci/plugins/badge/actions/JobBadgeAction/index.groovy

Reimplemented PRs #1 and #25

---

src/main/resources/org/jenkinsci/plugins/badge/actions/JobBadgeAction/index.groovy
src/main/resources/org/jenkinsci/plugins/badge/actions/RunBadgeAction/index.groovy

Add Bitbucket Markdown to docs

---

README.md

 Updated documentation for UnprotectedUrl

---

src/main/java/org/jenkinsci/plugins/badge/StatusImage.java

I think this is right for fixing https://issues.jenkins-ci.org/browse/JENKINS-56625
Building and testing an hpi now.  Edit: seems to work.

JENKINS-56625 Fix for too many open files

---

src/main/java/org/jenkinsci/plugins/badge/EmbeddableBadgeConfig.java
src/main/java/org/jenkinsci/plugins/badge/actions/EmbeddableBadgeConfigsAction.java
src/main/java/org/jenkinsci/plugins/badge/annotations/OptionalParam.java
src/main/java/org/jenkinsci/plugins/badge/annotations/Param.java
src/main/java/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStep.java

Purely code formatting changes

Consistent 4 space indentation

---

src/main/java/org/jenkinsci/plugins/badge/StatusImage.java
src/main/java/org/jenkinsci/plugins/badge/extensions/BuildParameterResolverExtension.java
src/main/java/org/jenkinsci/plugins/badge/extensions/BuildParameterRunSelectorExtension.java

Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
Fix build failures due to spotbugs

Fix all spotbugs

---

pom.xml

GitHub has dropped support for git:// protocol
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~

Use https protocol, not git protocol

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/badge/extensions/SpecialValueParameterResolverExtension.java

Builds on #83
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~

Use plugin bom

---

.github/release-drafter.yml

Use release drafter

---

.gitignore
.gitpod.Dockerfile
.gitpod.yml
.vscode/settings.json

Testing a new configuration
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~

Add gitpod development configuration

---

src/main/java/org/jenkinsci/plugins/badge/JobBadgeActionFactory.java
src/main/java/org/jenkinsci/plugins/badge/RunBadgeActionFactory.java
src/main/java/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStep.java

Adds some missing `@NonNull` annotations.
------------------------------

Add nullability annotations

---

src/main/java/org/jenkinsci/plugins/badge/StatusImage.java
src/test/java/org/jenkinsci/plugins/badge/StatusImageTest.java

- Add override annotation to a method
- Test more StatusImage cases
Cover more branches with the StatusImage automated test

Increase StatusImage test coverage

---

Jenkinsfile

Test Jenkins 2.361.2 and Jenkins 2.374

---

Jenkinsfile

Do not fail fast because most failures are transient or are specific to a single configuration.

Test all CI configurations to completion

---

src/test/java/org/jenkinsci/plugins/badge/ImageResolverTest.java

The allowed values are equivalent inside the tested code, so using any one of the allowed values should have the same final result.

Allow wider range of values in test

---

src/test/java/org/jenkinsci/plugins/badge/ImageResolverTest.java

Uses a JenkinsRule WebClient with a call to executeOnServer to provide a Stapler context for the call.
Found that technique in the Jenkins core WhoAmITest.  Learned something new about automated testing of Jenkins methods.
Thanks @Okhan-coder for the initial test and for the inspiration to learn more about the test methods available on JenkinsRule.

Test the real ImageResolver

---

src/test/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusActionTest.java

Add tests for `DoIcon()` , `DoIconForJob()` , `getUrlName()` , `getIconFileName()` , `getDisplayName()`  methods from [PublicBuildStatusAction,java](https://github.com/jenkinsci/embeddable-build-status-plugin/blob/master/src/main/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusAction.java)
See [JENKINS-70464](https://issues.jenkins.io/browse/JENKINS-70464) for more information

add test for PublicBuildStatusAction.java

---

.gitpod.Dockerfile
.gitpod.yml

The current Gitpod configuration does not work and results in an error. Also the use of `.gitpod.Dockerfile` is unnecessary. Rebuilt the complete configuration and tested by running it.

Fix Gitpod configuration 

---

README.md

- Remove trailing white space from docs
- Describe expected values for text variant
Confirmed text status strings in this pull request match the returned values.

Document text status strings

---

README.md

- Link to plugin site for docs
- Link to extension point documentation

Link to extensions documentation

---

src/test/java/org/jenkinsci/plugins/badge/EmbeddableBadgeConfigTest.java

Added tests for GetSubject to increase test coverage 

---

src/main/java/org/jenkinsci/plugins/badge/StatusImage.java
src/spotbugs/excludesFilter.xml

Spotbugs newer versions report these warnings that shouild be suppressed.
COmpiles as expected.
```[tasklist]
```

Suppress future spotbugs warning

---

src/test/java/org/jenkinsci/plugins/badge/ImageResolverTest.java
src/test/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusActionTest.java

No need to leak resources from the tests
Confirmed that automated tests pass

Use try with resources for WebClient

---

src/test/java/org/jenkinsci/plugins/badge/actions/JobBadgeActionTest.java
src/test/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusActionTest.java

Improve coverage the JobBadgeAction class and the StatusImage class.
Confirmed automated tests passed and coverage increased.

Add Job Badge Action Test

---

src/main/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusAction.java
src/test/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusActionTest.java

Add PublicBuildStatusAction  test
Added tests for PublicBuildStatusAction class and fixed a typo

Add test for PublicBuildStatusAction class and fixed a typo

---

src/main/java/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStep.java
src/test/java/org/jenkinsci/plugins/badge/dsl/AddEmbeddableBadgeConfigStepTest.java

Added tests for AddEmbeddableConfigStepTest class and changed the 'badgeConfig' field in the AddEmbeddableBadgeConfigStep from private to public to be used in the AddEmbeddableConfigStepTest class
Test automation passes.

Added tests for AddEmbeddableConfigStepTest class and changed AddEmbeddableBadgeConfigStep class

---

src/test/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusActionJobSelectorsTest.java
src/test/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusActionSecurityTest.java
src/test/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusActionTest.java

- added tests that cover all scenarios of private getProject method
- Because the method is private, I need to test it implicitly through doText and doIcon methods
- added helper methods for setting and cleaning security modifications in the method
#114

Add PublicBuildStatusAction tests

---

pom.xml
src/test/java/org/jenkinsci/plugins/badge/EmbeddableBadgeConfigTest.java
src/test/java/org/jenkinsci/plugins/badge/IconRequestHandlerTest.java
src/test/java/org/jenkinsci/plugins/badge/ImageResolverTest.java
src/test/java/org/jenkinsci/plugins/badge/ParameterResolverTest.java
src/test/java/org/jenkinsci/plugins/badge/StatusImageTest.java
src/test/java/org/jenkinsci/plugins/badge/actions/JobBadgeActionTest.java
src/test/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusActionJobSelectorsTest.java
src/test/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusActionSecurityTest.java
src/test/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusActionTest.java
src/test/java/org/jenkinsci/plugins/badge/actions/RunBadgeActionJenkinsRuleTest.java
src/test/java/org/jenkinsci/plugins/badge/actions/RunBadgeActionTest.java
src/test/java/org/jenkinsci/plugins/badge/extensions/BuildIdRunSelectorExtensionTest.java
src/test/java/org/jenkinsci/plugins/badge/extensions/BuildParameterResolverExtensionTest.java
src/test/java/org/jenkinsci/plugins/badge/extensions/BuildParameterRunSelectorExtensionTest.java
src/test/java/org/jenkinsci/plugins/badge/extensions/SpecialValueParameterResolverExtensionTest.java

This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.

Migrate tests to JUnit5
